### ISSUE TITLE
数据疑问

### ISSUE THREAD

**Issue by gxa1028** [logpai/loghub-2.0#6]
关于这篇文章：Logram: Efficient Log Parsing Using n-Gram Dictionaries
文章作者在文中给出的测试数据准确率平均值为0.825
您的代码跑出来的数据在全量数据集上
平均GA为0.340，平均PA为0.200
我想请问，你在该项目中对于上述文章的解析算法是复现还是直接使用文章作者的代码？
如果是直接使用，为何会产生如此大的差距？是数据集的原因还是其他原因？

**Comment by zhjiang22** [comment]
I used the implementation from [LogPAI/logparser](https://github.com/logpai/logparser). The original results were obtained using Loghub-2k. Since Loghub-2.0 is large-scale and more complex, the performance of syntax-based log parsers drops significantly. You can also run the benchmark yourself to reproduce the results.
