### ISSUE TITLE
doi link question

### ISSUE THREAD

**Issue by yunlibo** [logpai/loghub-2.0#8]
Why does the doi link in the paper say not found?

**Comment by zhjiang22** [comment]
Thank you for your interest! Are you referring to the DOI of this paper? If possible, could you please provide the DOI link you mentioned so I can better understand the situation. Many thanks! :)

**Comment by yunlibo** [comment]
Yes, I click on https://doi.org/10.1145/3650212.3652123, but didn't find it.  :(

**Comment by zhjiang22** [comment]
Got it. I have double-checked that the DOI link is correct. However, since the ISSTA conference is in Sep. 2024, it may take about two months for the DOI to be activated. In the meantime, you can access the pre-print of our camera-ready version on [arXiv](https://arxiv.org/abs/2308.10828). Thank you for your patience! :)
